version: '2'
services:
    repertoire-database:
        image: postgres:13.8-alpine
        user: postgres
        volumes:
            - ./local-initdb/:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: magical_password
        command: postgres -c 'max_connections=1000'
    repertoire-api:
        container_name: repertoire-api
        image: repertoire-api:latest
        volumes:
            - ../../app:/home/app:delegated
        depends_on:
            - repertoire-database
        links:
            - repertoire-database
        restart: on-failure
        environment:
            POSTGRES_DB_URI: postgresql+psycopg2://one:password@repertoire-database/repertoire
