x-postgres-env: &postgres-env
    POSTGRES_HOST: repertoire-database-dev
    POSTGRES_DATABASE: repertoire
    POSTGRES_PORT: 5432
    POSTGRES_USER: one
    POSTGRES_PASSWORD: password

x-base-backend: &base-backend
    image: repertoire-api-dev:latest
    volumes:
        - ../../app:/home/app:delegated
    depends_on:
        - repertoire-database-dev
    links:
        - repertoire-database-dev
    restart: on-failure
    environment:
        <<: *postgres-env
        POSTGRES_DB_URI: postgresql+psycopg2://one:password@repertoire-database-dev/repertoire
        CELERY_BROKER_URL: redis://repertoire-redis-dev:6379
        CELERY_RESULT_BACKEND: redis://repertoire-redis-dev:6379

version: '2'
services:
    repertoire-database-dev:
        image: postgres:16.3-alpine
        container_name: repertoire-database-dev
        user: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./hcl-initdb/:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: magical_password
        command: postgres -c 'max_connections=1000'
    repertoire-api-dev:
        <<: *base-backend
        container_name: repertoire-api-dev
        command: tail -f /dev/null
        ports:
            - "8080:8080"
