CREATE DATABASE onetest;
GRANT ALL PRIVILEGES ON DATABASE onetest TO postgres;

CREATE DATABASE onetest0;
GRANT ALL PRIVILEGES ON DATABASE onetest0 TO postgres;

CREATE DATABASE onetest1;
GRANT ALL PRIVILEGES ON DATABASE onetest1 TO postgres;

CREATE DATABASE onetest2;
GRANT ALL PRIVILEGES ON DATABASE onetest2 TO postgres;

CREATE DATABASE onetest3;
GRANT ALL PRIVILEGES ON DATABASE onetest3 TO postgres;