CREATE USER one WITH PASSWORD 'password';

CREATE DATABASE onetest;
GRANT ALL PRIVILEGES ON DATABASE onetest TO one;

CREATE DATABASE onetest0;
GRANT ALL PRIVILEGES ON DATABASE onetest0 TO one;

CREATE DATABASE onetest1;
GRANT ALL PRIVILEGES ON DATABASE onetest1 TO one;

CREATE DATABASE onetest2;
GRANT ALL PRIVILEGES ON DATABASE onetest2 TO one;

CREATE DATABASE onetest3;
GRANT ALL PRIVILEGES ON DATABASE onetest3 TO one;